name: fmriprep_docs
channels:
  - conda-forge
dependencies:
- python==3.5
- numpy>=1.11.0
- scipy=0.18.1
- scikit-learn=0.18.1
- matplotlib=2.0.0
- traits=4.6
- jinja2=2.8
- sphinx>=1.5.1
- sphinx_rtd_theme
- mock
- future
- nibabel
- statsmodels
- xvfbwrapper
- funcsigs
- networkx
- python-dateutil
- pydotplus
- cython

- pip:
    - sphinx-argparse
    - doctest-ignore-unicode
    - svgutils
    - nitime
    - nilearn
    - git+https://github.com/poldracklab/niworkflows.git@841c3296fd5a8c1fe336806662482d63e2a623e8#egg=niworkflows-0.1.6-dev
